### ISSUE TITLE
typo and omission

### ISSUE THREAD

**Issue by i-make-robots** [norlab-ulaval/awesome-canadian-robotics#2]
"A curated list of Canadian robotics open-source software, compagnies and researchers. "
compagnies should be "companies"

In Vancouver BC there is also Marginally Clever Robots, Ltd.

**Comment by pomerlef** [comment]
Thanks @i-make-robots , the typo is fixed with 6d54a9c.

As for the [Marginally Clever Robots](https://www.marginallyclever.com/), what would be the category?

**Comment by i-make-robots** [comment]
We make both open source software and robots.  so both are applicable.  your call.

**Comment by i-make-robots** [comment]
the "about" section on github still has the typo.

**Comment by IamPhytan** [comment]
> We make both open source software and robots. so both are applicable. your call.

For the robots part, am I right to say that, according to your website, you are building artistic robots ?

**Comment by pomerlef** [comment]
The "About" is fixed. Thanks for pointing that out.

I can see on your website:
> What’s with the moon stuff, then? Our long-term goal is to have our robots sustainably building 3D printed moon bases, while we are making accessible jobs and solutions for people on Earth. 

Our categories for now are:

- [Startups](https://github.com/norlab-ulaval/awesome-canadian-robotics#startups)
- [Robot manufacturers](https://github.com/norlab-ulaval/awesome-canadian-robotics#robot-manufacturers)
- [Aerospace](https://github.com/norlab-ulaval/awesome-canadian-robotics#aerospace)
- [Natural Resources](https://github.com/norlab-ulaval/awesome-canadian-robotics#natural-resources)
- [Warehouse Robotics](https://github.com/norlab-ulaval/awesome-canadian-robotics#warehouse-robotics)

So, either Startups, Aerospace or we add a section for Art.

**Comment by i-make-robots** [comment]
Robot manufacturers.
